server:
  port: 8080
  servlet:
    contextPath: /
    
spring:
  flyway:
    locations: classpath:/sql
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:bank_details
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
