server:
  port: 8080
  context-path: /restful-microservice
  
debug: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://192.168.1.4:5432/spring_boot_rest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
