server:
  port: 8080
  servlet:
    contextPath: /
  
logging:
  level:
    root: INFO
    com.swayam.demo: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

spring:
  flyway:
    locations: classpath:/sql
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:bank_details
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

grpc:
  server:
    port: 50051    